#!/usr/bin/env bash



# Git aliases

alias push='git push'
alias s='git s'
alias pull='git pull'
alias ci='git ci'
alias lg='git lg'
alias add='git add'
alias d='git d'
alias dc='git dc'
alias st='git stash'
alias sp='git sp'
alias pom='git pom'
alias pum='git pum'
alias clone='git clone'
alias co='git co'
alias cot='git cot'
alias b='git b'



