#!/bin/bash -   
#title          :_shellopts
#description    :shell option sets for BASH
#author         :http://github.com/iambryan
#date           :20150111
#version        :0.1    
#notes          :       
#============================================================================

shopt -s histappend histreedit histverify

# Ignore duplicate entries and don't log commands with a leading space
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=3000
HISTFILESIZE=5000
HISTIGNORE="&:ls:ls *:[bf]g:exit"