#!/bin/bash -   
#title          :_shellopts
#description    :shell option sets for BASH
#author         :http://github.com/iambryan
#date           :20151004
#version        :0.1    
#notes          :       
#============================================================================

shopt -s cdable_vars
shopt -s cdspell
shopt -s cdable_vars
shopt -s checkhash
shopt -s checkwinsize
shopt -s sourcepath
shopt -s no_empty_cmd_completion
shopt -s nocaseglob
shopt -s extglob
