#!/bin/bash

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases



#  ls -A --group-directories-first "$@"
alias ls='ls --color=auto'
alias ld='ls -al -d * | egrep "^d"' # only subdirectories
alias ll='ls -alF'
alias lg="ls -lv --group-directories-first"
alias l='ls -alF'
alias la='ll -AF --group-directories-first'
alias ls='ls -lh --color'
alias lx='ls -lXB'         #  Sort by extension.
alias lk='ls -lSr'         #  Sort by size, biggest last.
alias lt='ls -ltr'         #  Sort by date, most recent last.
alias lc='ls -ltcr'        #  Sort by/show change time,most recent last.
alias lu='ls -ltur'        #  Sort by/show access time,most recent last.
alias lr='ll -R'           #  Recursive ls.
alias tree='tree -Csuh'    #  Nice alternative to 'recursive ls' ...
alias recent='ls -alt | head -20' # recently changed files

alias md='mkdir -p'			#  Makes parent directories as needed
alias mkdir='md'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias psg='ps -A | grep'

# Typo fixes

alias xs='cd'
alias vf='cd'
alias moer='more'
alias moew='more'
alias kk='ll'











alias whereami='display_info'